#!/usr/bin/env bash

# Define variables
key_name="school"
bits=4096
passphrase="betty"
key_directory="$HOME/.ssh"
private_key="$key_directory/$key_name"

# Create the RSA key pair
ssh-keygen -t rsa -b 4096 -N "betty" -f "$HOME/.ssh/school"
