#!/usr/bin/env bash
# Update Nginx configuration
sed -i 's/user\s*nginx;/user nginx;\n\tlisten 8080;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
if [ $? -eq 0 ]; then
    service nginx restart
fi
