#!/usr/bin/env bash
# Update Nginx configuration
sed -i 's/user\s*nginx;/user nginx;\n\tlisten 8080;/g' /etc/nginx/nginx.conf

# Modify Nginx default site configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart
