#!/usr/bin/env bash
# Update Nginx configuration
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
