#!/usr/bin/env bash
#Nginx is running as the nginx user
sed -i 's/user\s*nginx;/user nginx;\n\tlisten 8080;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
