#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_route="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/Justice00000;\n\t}"
sudo sed -i "/server_name _;/c\\$new_route" /etc/nginx/sites-enabled/default

sudo service nginx restart
